services:
  postgres:
    image: postgres:17.6
    container_name: ecoresiduos-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ecoresiduos
      POSTGRES_DB: ecoresiduos_db
    ports:
      - "5432:5432"
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/dump.sql